server:
  port: 8080

eureka:
  instance:
    #??ip
    hostname: 8.137.159.138
  client:
    #??????????
    register-with-eureka: false
    #??????
    fetch-registry: false
    #??url
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/