eureka:
  client:
    serviceUrl:
      defaultZone: http://8.137.159.138:8080/eureka/

server:
  port: 8086

spring:
  application:
    name: herb-research-service
  datasource:
    url: jdbc:mysql://localhost:3306/his_research
    username: root
    password: Liu12345