eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8088

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/his_comment
    username: root
    password: gq
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB