eureka:
  client:
    serviceUrl:
      defaultZone: http://8.137.159.138:8080/eureka/

server:
  port: 8088

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/his_comment
    username: root
    password: Liu12345
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# 敏感词过滤配置
sensitive:
  word:
    enabled: true
    use-database: true        # 是否使用数据库存储敏感词
    replacement: "***"
    log-sensitive-words: true
    severe-strategy: REJECT  # 严重敏感词处理策略：REJECT-拒绝发布，FILTER-过滤后发布
    mild-strategy: FILTER    # 轻度敏感词处理策略：REJECT-拒绝发布，FILTER-过滤后发布
    enable-check-api: true
    max-sensitive-words: 10