server:
  port: 8090

spring:
  application:
    name: his-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':  #允许跨域访问的资源
                allowedOrigins: "*" #跨域允许的来源
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"

          routes:
            - id: user-service-provider
              uri: lb://user-service-provider
              predicates:
                - Path=/user-service/hello
              filters:
                - StripPrefix=1

            #登录认证
            - id: his-user-service-auth
              uri: lb://his-user-service
              predicates:
                - Path=/auth/*

            #管理员用户管理
            - id: his-user-service-root
              uri: lb://his-user-service
              predicates:
                - Path=/his-user-service/root/**
              filters:
                - StripPrefix=1
                - name: JwtRootAuth

            #用户服务
            - id: his-user-service
              uri: lb://his-user-service
              predicates:
                - Path=/his-user-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #中药信息(地理位置 成长记录)
            - id: herb-info-service
              uri: lb://herb-info-service
              predicates:
                - Path=/herb-info-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #研究内容(仅学生)
            - id: herb-research-service
              uri: lb://herb-research-service
              predicates:
                - Path=/herb-research-service/**
              filters:
                - StripPrefix=1
                - name: JwtStudentAuth

            #课程评分（所有登录用户可用）
            - id: herb-teaching-service-rate
              uri: lb://herb-teaching-service
              predicates:
                - Path=/herb-teaching-service/courses/*/ratings
                - Method=POST
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #课程收藏（所有登录用户可用）
            - id: herb-teaching-service-collect
              uri: lb://herb-teaching-service
              predicates:
                - Path=/herb-teaching-service/courses/*/collections
                - Method=POST,DELETE
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #课程管理(仅教师、管理员)
            - id: herb-teaching-service-write
              uri: lb://herb-teaching-service
              predicates:
                - Path=/herb-teaching-service/**
                - Method=POST,PUT,DELETE
              filters:
                - StripPrefix=1
                - name: JwtTeacherAuth

            #课程查看
            - id: herb-teaching-service-read
              uri: lb://herb-teaching-service
              predicates:
                - Path=/herb-teaching-service/**
                - Method=GET
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #培训资料
            - id: herb-training-service
              uri: lb://herb-training-service
              predicates:
                - Path=/herb-training-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #评论
            - id: comment-service
              uri: lb://comment-service
              predicates:
                - Path=/comment-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/