server:
  port: 8090

spring:
  application:
    name: his-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':  #允许跨域访问的资源
                allowedOrigins: "*" #跨域允许的来源
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"

          routes:
            - id: user-service-provider
              uri: lb://user-service-provider
              predicates:
                - Path=/user-service/hello
              filters:
                - StripPrefix=1

            #登录认证
            - id: his-user-service-auth
              uri: http://8.137.146.15:8081
              predicates:
                - Path=/auth/**

            #教师用户服务
            - id: his-user-service-teacher
              uri: http://8.137.146.15:8081
              predicates:
                - Path=/his-user-service/teacher/**
              filters:
                - StripPrefix=1
                - name: JwtTeacherAuth

            #管理员用户管理
            - id: his-user-service-root
              uri: http://8.137.146.15:8081
              predicates:
                - Path=/his-user-service/root/**
              filters:
                - StripPrefix=1
                - name: JwtRootAuth

            #用户服务
            - id: his-user-service
              uri: http://8.137.146.15:8081
              predicates:
                - Path=/his-user-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #中药信息 成长记录管理
            - id: herb-info-service-growth-manage
              uri: http://8.137.146.15:8083
              predicates:
                - Path=/herb-info-service/root/**
              filters:
                - StripPrefix=1
                - name: JwtRootAuth

            #中药信息(地理位置 成长记录)
            - id: herb-info-service
              uri: http://8.137.146.15:8083
              predicates:
                - Path=/herb-info-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #研究内容(仅学生)
            - id: herb-research-service
              uri: http://8.148.30.255:8086
              predicates:
                - Path=/herb-research-service/**
              filters:
                - StripPrefix=1
                - name: JwtStudentAuth

            #课程评分（所有登录用户可用）
            - id: herb-teaching-service-rate
              uri: http://47.122.113.158:8084
              predicates:
                - Path=/herb-teaching-service/courses/*/ratings
                - Method=POST
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #课程收藏（所有登录用户可用）
            - id: herb-teaching-service-collect
              uri: http://47.122.113.158:8084
              predicates:
                - Path=/herb-teaching-service/courses/*/collections
                - Method=POST,DELETE
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #课程管理(仅教师、管理员)
            - id: herb-teaching-service-write
              uri: http://47.122.113.158:8084
              predicates:
                - Path=/herb-teaching-service/**
                - Method=POST,PUT,DELETE
              filters:
                - StripPrefix=1
                - name: JwtTeacherAuth

            #课程查看
            - id: herb-teaching-service-read
              uri: http://47.122.113.158:8084
              predicates:
                - Path=/herb-teaching-service/**
                - Method=GET
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #培训资料
            - id: herb-training-service
              uri: http://localhost:8087
              predicates:
                - Path=/herb-training-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #敏感词管理（仅管理员权限）
            - id: sensitive-word-service-admin
              uri: http://47.122.113.158:8088
              predicates:
                - Path=/comment-service/admin/sensitive-words/**
              filters:
                - StripPrefix=1
                - name: JwtRootAuth

            #评论
            - id: comment-service
              uri: http://47.122.113.158:8088
              predicates:
                - Path=/comment-service/**
              filters:
                - StripPrefix=1
                - name: JwtAuth

            #业绩审核相关操作（仅管理员权限）
            - id: performance-service-audit
              uri: http://8.148.30.255:8089
              predicates:
                - Path=/performance-service/performances/*/audit
                - Method=POST
              filters:
                - StripPrefix=1
                - name: JwtRootAuth

            #业绩待审核列表（仅管理员权限）
            - id: performance-service-pending
              uri: http://8.148.30.255:8089
              predicates:
                - Path=/performance-service/performances/pending
                - Method=GET
              filters:
                - StripPrefix=1
                - name: JwtRootAuth

            #业绩管理其他操作（教师和管理员权限）
            - id: performance-service-write
              uri: http://8.148.30.255:8089
              predicates:
                - Path=/performance-service/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - StripPrefix=1
                - name: JwtTeacherAuth



eureka:
  client:
    serviceUrl:
      defaultZone: http://8.137.159.138:8080/eureka/