server:
  port: 8090

spring:
  application:
    name: his-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':  #允许跨域访问的资源
                allowedOrigins: "*" #跨域允许的来源
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE

          routes:
            - id: user-service-provider
              uri: lb://user-service-provider
              predicates:
                - Path=/user-service/hello
              filters:
                - StripPrefix=1
            - id: herb-info-service
              uri: lb://herb-info-service
              predicates:
                - Path=/herb-info-service/**
              filters:
                - StripPrefix=1
            - id: Research
              uri: lb://research
              predicates:
                - Path=/research/**
              filters:
                - StripPrefix=1



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/