eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8087
  address: 0.0.0.0  # 监听所有网络接口

spring:
  application:
    name: herb-training-service
  datasource:
    url: jdbc:mysql://localhost:3306/his_material
    username: root
    password: Liu12345

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

live:
  srs:
    server-url: rtmp://192.168.195.100:1935/live
    api-url: http://192.168.195.100:1985/api
    http-flv-url: http://192.168.195.100:8095/live
    hls-url: http://192.168.195.100:8095/live/hls
  record:
    save-path: /hisData/record
  push:
    key-check-enabled: false
    auth-expire: 86400  # 24小时，单位秒
    auth-key: his_key

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: live-recordings