eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8087

spring:
  application:
    name: herb-training-service
  datasource:
    url: jdbc:mysql://localhost:3306/his_material
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB