eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8085

spring:
  application:
    name: EvaluationAndDeclaration
  datasource:
    url: jdbc:mysql://localhost:3306/herb_rating
    username: root
    password: 123456