eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8080/eureka/

server:
 port: 8083

spring:
 application:
  name: herb-info-service
 datasource:
  url: jdbc:mysql://localhost:3306/his_herbinfo
  username: root
  password: Liu12345
 servlet:
  multipart:
   enabled: true
   max-file-size: 10MB
   max-request-size: 10MB